[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"
  functions = "../netlify/functions"
  
[build.environment]
  PYTHON_VERSION = "3.9"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
